name: Your Github Workflow name
on:
  schedule:
  - cron: "0/1 * * * *"


jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - run: pip3 install Beautifulsoup4
      - run: python card_downloader.py
      
